[Person]
email = "Email"
gender = "Gender"
nationality = "Nationality"
givenName = "First Name"
familyName = "Surname"
funder = "[Beneficiary No]"
identifier = "Personal identifier \ne.g ORCID (optional)"
name = "Full Name"
