from pathlib import Path

import pandas as pd

from metadata_converter.biosamples_handling import (
    extract_sample,
    extract_sampling_action,
    get_metadata,
)
from metadata_converter.load import load_to_jsonld
from metadata_converter.schema_org_models.schemaorg_models import Action, Product
from metadata_converter.transform import convert_to_long
from metadata_converter.transform_helpers import create_full_names, split_field


def wide(df: pd.DataFrame) -> pd.DataFrame:
    return df.pivot(index="id", columns="header", values="value")


def get_one_to_many_id_mapping(
    addend: pd.DataFrame,
    source: pd.DataFrame,
    addend_header: str,
    source_header: str,
    id_header: str,
) -> pd.DataFrame:
    ids = (
        addend.loc[addend.header == addend_header, ["id", "value"]]
        .merge(
            source[[source_header, "@id"]],
            left_on="value",
            right_on=source_header,
        )
        .drop(columns="value")
        .rename(columns={"@id": "value"})
        .assign(header=id_header)[["id", "header", "value"]]
    )
    return ids


def preprocess_datahub(data_dict: dict[str, pd.DataFrame]) -> dict[str, pd.DataFrame]:
    # hardcode the sheet names for now
    author_sheet = "author"
    dataset_sheet = "dataset"
    analysis_sheet = "analysis"
    sample_sheet = "sample"

    # ====== handle authors ======

    # just add the full names
    data_dict[author_sheet] = create_full_names(data_dict[author_sheet])

    # ====== handle main Dataset ======

    # add the people as creators
    authors_w = wide(data_dict[author_sheet])
    # checks that the author is creator and get his @id to do the linking
    creators = authors_w[authors_w["author:is-dataset-author"] == 1]["@id"]
    # bring it in the right format and add header and id colum
    creators = creators.rename("value").to_frame().assign(header="creator_id", id="0")
    data_dict[dataset_sheet] = pd.concat(
        [data_dict[dataset_sheet], creators], ignore_index=True
    )

    # split keywords entries into separate rows
    data_dict[dataset_sheet] = split_field(data_dict[dataset_sheet], "dataset:keywords")

    # ====== handle samples ======

    # download the corresponding metadata
    samples_w = wide(data_dict[sample_sheet])
    for sample_id in samples_w["sample:pid"].unique():
        meta_data = get_metadata(sample_id)
        product_dict = extract_sample(meta_data, sample_id)
        product_dict.pop("@context")
        product = Product(**product_dict)
        action_dict = extract_sampling_action(meta_data, sample_id)
        action_dict.pop("@context")
        action = Action(**action_dict)
        load_to_jsonld(product, output_path=Path("output"))
        load_to_jsonld(action, output_path=Path("output"))

    # replace the autogenerated @id with the actually used one
    samples_w["@id"] = samples_w["sample:pid"].apply(lambda x: f"Product_{x}.jsonld")

    # remove the samples from the final dataset, as we do not want to create schemas from it
    data_dict.pop(sample_sheet)

    # ====== handle analysis ======

    # split author entries into separate rows
    data_dict[analysis_sheet] = split_field(
        data_dict[analysis_sheet], "analysis:author-pid"
    )

    # add the @id of the authors to do the linking
    analysis = data_dict[analysis_sheet]
    agents = analysis.loc[analysis.header == "analysis:author-pid"]
    agents["header"] = "agent_id"
    agents["value"] = agents["value"].apply(
        lambda v: authors_w.loc[authors_w["author:pid"] == v, "@id"].values[0]
    )

    # add samples as objects
    samples = (
        analysis.loc[analysis.header == "analysis:pid", ["id", "value"]]
        .merge(
            samples_w[["sample:analysis-pid", "@id"]],
            left_on="value",
            right_on="sample:analysis-pid",
        )
        .drop(columns="value")
        .rename(columns={"@id": "value"})
        .assign(header="sample_id")[["id", "header", "value"]]
    )

    data_dict[analysis_sheet] = pd.concat(
        [data_dict[analysis_sheet], agents, samples], ignore_index=True
    )

    return data_dict
