from pathlib import Path

import pandas as pd

from metadata_converter.flat_data.transform_helpers import (
    create_full_names,
    split_field,
)
from metadata_converter.linked_data.biosamples_handling import (
    extract_sample,
    extract_sampling_action,
    get_metadata,
)
from metadata_converter.load import load_to_jsonld
from metadata_converter.schema_org_models.schemaorg_models import Action, Product


def wide(df: pd.DataFrame) -> pd.DataFrame:
    return df.pivot(index="id", columns="header", values="value")


def get_one_to_many_id_mapping(
    addend: pd.DataFrame,
    source: pd.DataFrame,
    addend_header: str,
    source_header: str,
    id_header: str,
) -> pd.DataFrame:
    ids = (
        addend.loc[addend.header == addend_header, ["id", "value"]]
        .merge(
            source[[source_header, "@id"]],
            left_on="value",
            right_on=source_header,
        )
        .drop(columns="value")
        .rename(columns={"@id": "value"})
        .assign(header=id_header)[["id", "header", "value"]]
    )
    return ids


def preprocess_datahub(data_dict: dict[str, pd.DataFrame]) -> dict[str, pd.DataFrame]:
    # hardcode the sheet names for now
    author_sheet = "author"
    dataset_sheet = "dataset"
    analysis_sheet = "analysis"
    sample_sheet = "sample"
    file_sheet = "file"

    # create some wide representations for simpler handling
    authors_w = wide(data_dict[author_sheet])
    samples_w = wide(data_dict[sample_sheet])
    files_w = wide(data_dict[file_sheet])

    # ====== handle authors ======

    # just add the full names
    data_dict[author_sheet] = create_full_names(data_dict[author_sheet])

    # ====== handle main Dataset ======

    # add the people as creators
    # checks that the author is creator and get his @id to do the linking
    creators = authors_w[authors_w["author:is-dataset-author"] == 1]["@id"]
    # bring it in the right format and add header and id colum
    creators = creators.rename("value").to_frame().assign(header="creator_id", id="0")
    data_dict[dataset_sheet] = pd.concat(
        [data_dict[dataset_sheet], creators], ignore_index=True
    )

    # split keywords entries into separate rows
    data_dict[dataset_sheet] = split_field(data_dict[dataset_sheet], "dataset:keywords")

    # ====== handle samples ======

    # download the corresponding metadata
    for sample_id in samples_w["sample:pid"].unique():
        meta_data = get_metadata(sample_id)
        product_dict = extract_sample(meta_data, sample_id)
        product_dict.pop("@context")
        product = Product(**product_dict)
        action_dict = extract_sampling_action(meta_data, sample_id)
        action_dict.pop("@context")
        action = Action(**action_dict)
        load_to_jsonld(product, output_path=Path("output"))
        load_to_jsonld(action, output_path=Path("output"))

    # we need the mapping between sample and analysis from the sample sheet, but
    # we do not need these data for creating .jsonld files, as the desired data
    # are already created in the download above.
    # Thus, we replace the autogenerated @id with the actually used one and use this df for mapping:
    samples_w["@id"] = samples_w["sample:pid"].apply(lambda x: f"Product_{x}.jsonld")
    # and remove the samples from the final dataset, as we do not want to create schemas from it
    data_dict.pop(sample_sheet)

    # ====== handle analysis ======
    analysis = data_dict[analysis_sheet]
    analysis_concat_list = []

    # split author entries into separate rows
    analysis = split_field(analysis, "analysis:author-pid")
    analysis_concat_list.append(analysis)

    # add the @id of the authors to do the linking
    agent_ids = get_one_to_many_id_mapping(
        addend=analysis,
        source=authors_w,
        addend_header="analysis:author-pid",
        source_header="author:pid",
        id_header="agent_id",
    )
    analysis_concat_list.append(agent_ids)

    # add samples as objects
    sample_ids = get_one_to_many_id_mapping(
        addend=analysis,
        source=samples_w,
        addend_header="analysis:pid",
        source_header="sample:analysis-pid",
        id_header="sample_id",
    )
    analysis_concat_list.append(sample_ids)

    # add datasets as results
    # the analysis field in the file sheet is optional, thus we have to check whether a mapping is actually provided
    missing_analysis = pd.isna(files_w["file:analysis"])
    if all(missing_analysis):
        print(
            "No analysis was provided in the input file's 'file' sheet. "
            "If only one analysis is provided, check whether this was used "
            "to create all files and adopt the input data accordingly or "
            "consider changing the behaviour of the code, if the datahub "
            "team can confirm that this assumption is true.\n"
        )
    elif sum(missing_analysis) > 0:
        print("Some files are missing a link to the analysis:")
        for file in files_w[pd.isna(files_w["file:analysis"])]["file:name"]:
            print(f"  - missing analysis for {file}")
        print("\n")
    else:
        results = get_one_to_many_id_mapping(
            addend=analysis,
            source=files_w,
            addend_header="analysis:pid",
            source_header="file:analysis",
            id_header="file_id",
        )
        analysis_concat_list.append(results)
    data_dict[analysis_sheet] = pd.concat(analysis_concat_list, ignore_index=True)

    # ====== handle file ======
    files = data_dict[file_sheet]
    file_concat_list = []

    # split the samples, if there should be multiple
    files = split_field(files, "file:sample")
    file_concat_list.append(files)

    # add samples as about
    # the sample field in the file sheet is optional, thus we have to check whether a mapping is actually provided
    missing_sample = pd.isna(files_w["file:sample"])
    if all(missing_sample):
        print("No samples were provided in the input file's 'file' sheet.\n")
    elif sum(missing_sample) > 0:
        print("Some files are missing a link to the sample:")
        for file in files_w[pd.isna(files_w["file:sample"])]["file:name"]:
            print(f"  - missing sample for {file}")
        print("\n")
    else:
        results = get_one_to_many_id_mapping(
            addend=files,
            source=samples_w,
            addend_header="file:sample",
            source_header="sample:pid",
            id_header="sample_id",
        )
        file_concat_list.append(results)
    data_dict[file_sheet] = pd.concat(file_concat_list, ignore_index=True)

    return data_dict
