[input]
file_path = "examples/ReportingContinuous_WP1.xlsx"

[input.extractor]
type = "excel"
sheet_name = "Publications"
header = 0
skiprows = [0, 1, 2, 3, 5, 6]
[input.cleaning]
strip_header_whitespace = true
strip_cell_whitespace = true
sentinels_to_na = true
empty_sentinels = ["", "N/A", "n/a", "-", "Please select"]
placeholders_to_na = true
plugin_dir = "plugins"

[output]
output_path = "output"

[mapping]
[mapping.ScholarlyArticle]
url = "Link to publication (if no PID of publication)"
identifier = [
    { type = "ISSN", value = "ISSN/ eSSN (if book insert ISBN)" },
    { type = "PropertyValue", value = "PID of deposited publication" }
]
name = "Title of the publication (for book chapters: title of chapter not of book)"
creator.type = "Person"
creator.name = "Authors"
isPartOf = "Title of the journal or equivalent"
publisher.type = "Organization"
publisher.name = "Publisher"
datePublished = "Month/ Year of publication"
license = "License type"