[input]
file_path = "/home/japlan001/Nextcloud/B5D_Datahub/input/Dataset_Alien_Tara4TREC_Biocean5D_version_1_export.xlsx"

[input.extractor]
type = "excel"
sheet_name = ["dataset", "author", "analysis", "sample", "file"]
header = 0
skiprows = [1, 2]
[input.cleaning]
strip_header_whitespace = true
strip_cell_whitespace = true
sentinels_to_na = false
placeholders_to_na = false
plugin_dir = "plugins"
plugin_name = "add_funding_info.py"

[output]
output_path = "output"

[mapping]
[mapping.author]
type = "Person"
id = "@id"
email = "author:email"
name = "name"
givenName = "author:first-name"
familyName = "author:last-name"
identifier.type = "Orcid"
identifier.value = "author:pid"
affiliation.type = "Organization"
affiliation.name = "author:affiliation"
funding.type = "Grant"
funding.id = "Grant ID"
memberOf.type = "Project"
memberOf.id = "Project ID"

[mapping.dataset]
type = "Dataset"
id = "@id"
name = "dataset:title"
creator.type = "Person"
creator.id = "creator_id"
abstract = "dataset:description"
identifier = "dataset:pid"
dateCreated = "dataset:date-first-created"
dateModified = "dataset:date-last-updated"
datePublished = "dataset:date-public"
inLanguage = "dataset:language"
keywords = "dataset:keywords"
funding.type = "Grant"
funding.id = "Grant ID"
sourceOrganization.type = "Project"
sourceOrganization.id = "Project ID"

[mapping.analysis]
type = "Action"
id = "@id"
name = "analysis:title"
identifier = "analysis:pid"
agent.type = "Person"
agent.identifier = "agent_id"
object.type = "Thing"
object.identifier = "sample_id"

[mapping.sample]
type = "Product"
id = "@id"
identifier = "sample:pid"

[mapping.file]
type = "Dataset"
id = "@id"
name = "file:name"
encodingFormat = "file:format"
description = "file:description"
comment = "file:comment"