[input]
file_path = "examples/ReportingContinuous_WP3.xlsx"

[input.extractor]
type = "excel"
sheet_name = "Researchers"
header = 0
skiprows = [0, 1, 3, 4]
[input.cleaning]
strip_header_whitespace = true
strip_cell_whitespace = true
normalize_empty_to_nan = true
placeholders_to_nan = true
empty_sentinels = ["", "N/A", "n/a", "-", "Please select"]

[output]
output_path = "output"

[mapping]
[mapping.Person]
email = "Email"
gender = "Gender"
nationality = "Nationality"
givenName = "First Name"
familyName = "Surname"
funder = "[Beneficiary No]"
identifier = "Personal identifier e.g. ORCID (optional)"
name = "First Name + Surname"