workflow_type = "biosamples"

[input]
input_path = "/home/japlan001/Nextcloud/B5D_Datahub/input"
sheet_name = "sample"
header = 0
skiprows = [1, 2]
header_name = "sample:pid"

[output]
output_path = "output/biosamples"