[input]
file_path = "examples/ReportingContinuous_WP1.xlsx"

[input.extractor]
type = "excel"
sheet_name = "Publications"
header = 0
skiprows = [0, 1, 2, 3, 5, 6]
[input.cleaning]
strip_header_whitespace = true
strip_cell_whitespace = true
sentinels_to_na = true
empty_sentinels = ["", "N/A", "n/a", "-", "Please select"]
placeholders_to_na = true
plugin_dir = "plugins"

[output]
output_path = "output"

[mapping]
[mapping.ScholarlyArticle]
url = "Link to publication (if no PID of publication)"
identifier = { type = "DOI", value = "PID of deposited publication" }
name = "Title of the publication (for book chapters: title of chapter not of book)"
creator.type = "Person"
creator.name = "Authors"
isPartOf.type = "Periodical"
isPartOf.name = "Title of the journal or equivalent"
isPartOf.identifier.type = "ISSN"
isPartOf.identifier.value = "ISSN/ eSSN (if book insert ISBN)"
publisher.type = "Organization"
publisher.name = "Publisher"
datePublished = "Month/ Year of publication"
license = "License type"
funding.type = "Grant"
funding.id = "Grant ID"
sourceOrganization.type = "Project"
sourceOrganization.id = "Project ID"